export enum PermissionEnum {
  UseRoleManagement = 'User & Role Management',
  CustomerList = 'Customer - Customer List',
  CustomerRegulatoryMonitoring = 'Customer - Regulatory Monitoring',
  AgentProfile = 'Agent - Agent Profile',
  AgentCustomerService = 'Agent - Customer Service',
  CommissionTSRIncentiveRate = 'Commission - TSR Incentive Rate',
  CommissionPayment = 'Commission - Payment',
  CommissionAgentFeeReport = 'Commission - Agent Fee Report',
  OrderTransaction = 'Order - Transaction',
  OrderVulnerableTransaction = 'Order - Vulnerable Transaction',
  OrderPlacement = 'Order - Order Placement',
  FundData = 'Fund Data',
  CustomNotification = 'Custom Notification',
  Content = 'Content',
  AuditRisk = 'Audit Risk',
  News = 'News',
  IndexType = 'Index Type',
  FundIndex = 'Fund Index',
  FundsAllIndex = 'Funds All Index',
}
