/**
 * Smart security Tossakan Admin Gateway
 *
 * API version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Injectable } from '@angular/core';
import { RequestResetPasswordDTO, ResetPasswordDTO } from '@model';
import { PnApiClientService } from '@postnerd-core';
import { Observable } from 'rxjs';
import { apiBaseUrl } from '../api-base-url';

@Injectable({
  providedIn: 'root',
})
export class AuthService {

  constructor(
    protected api: PnApiClientService) {
  }

  public authResetPasswordPost$(body: ResetPasswordDTO): Observable<any> {
    return this.api.post(`${apiBaseUrl()}/reset-password`, body, undefined, true);
  }

  public authRequestResetPasswordPost$(body: RequestResetPasswordDTO): Observable<any> {
    return this.api.post(`${apiBaseUrl()}/request-reset-password`, body, undefined, true);
  }

}
