import {AddressIdDocumentDTO} from './AddressIdDocumentDTO';
import {AddressCurrentDTO} from './AddressCurrentDTO';
import {OccupationInformDTO} from './OccupationInformDTO';
import {AddressWorkDTO} from './AddressWorkDTO';
import {AddressMailDTO} from './AddressMailDTO';
import {IncomeSourceDTO} from './IncomeSourceDTO';
import {AccountFileDTO} from './AccountFileDTO';

export interface CustomerProfileDTO {
  accountFiles: AccountFileDTO[];
  accountStatus: string;
  addressCurrent: AddressCurrentDTO;
  addressIdDocument: AddressIdDocumentDTO;
  addressMail: AddressMailDTO;
  addressWork: AddressWorkDTO;
  agentCode: string;
  bankApprove: boolean;
  bankConnect: boolean;
  birthdate: string;
  cardExpiredDate: string;
  cardNumber: string;
  cddNo3: boolean;
  cddScore: string;
  currentAddressFlag: string;
  dcaFlag: boolean;
  email: string;
  enFirstname: string;
  enLastname: string;
  evaluateDate: string;
  fatca: boolean;
  fax: string;
  fcnAccountIds: string[];
  id: number;
  identificationCardType: string;
  incomeSource: IncomeSourceDTO;
  mailAddressFlag: string;
  mailMethod: string;
  maritalStatus: string;
  mobileNumber: string;
  nationality: string;
  occupationInform: OccupationInformDTO;
  passportCountry: string;
  profileImageUrl: string;
  relatedPoliticalPerson: boolean;
  reviewDate: string;
  riskLevel: number;
  thFirstname: string;
  thLastname: string;
  title: string;
  vulnerableFlag: boolean;
  workAddressFlag: string;
}
