import {IdDocumentAddressDTO} from './IdDocumentAddressDTO';
import {CurrentAddressDTO} from './CurrentAddressDTO';
import {MailingAddressDTO} from './MailingAddressDTO';
import {WorkAddressDTO} from './WorkAddressDTO';
import {CddScoreDTO} from './CddScoreDTO';
import {RiskLevelDTO} from './RiskLevelDTO';

export interface OpenAccountDTO {
  accountStatus: string;
  accountType: string;
  accountVerifyType: string;
  assetValue: number;
  applicationDate: Date;
  bankBranchName: string;
  bankCode: string;
  bankName: string;
  bankNo: string;
  birthdate: Date;
  branchCode: string;
  businessTypeId: string;
  businessTypeOther: string;
  cardExpiredDate: string;
  cardNumber: string;
  cddDate: Date;
  cddNo3: boolean;
  cddNo3Choice: string;
  cddNo4Choice: string;
  cddScoreDTO: CddScoreDTO;
  companyName: string;
  currentAddress: CurrentAddressDTO;
  currentAddressFlag: string;
  email: string;
  enFirstname: string;
  enLastname: string;
  fatca: boolean;
  icLicense: string;
  icTeam: string;
  id: number;
  idDocumentAddress: IdDocumentAddressDTO;
  identificationCardType: string;
  incomeSource: string;
  incomeSourceCountry: string;
  incomeSourceOther: string;
  investmentObjective: string;
  investmentObjectiveOther: string;
  isDraft: boolean;
  mailAddressFlag: string;
  mailMethod: string;
  mailingAddress: MailingAddressDTO;
  maritalStatus: string;
  mobileNumber: string;
  monthlyIncomeLevel: string;
  nationality: string;
  occupationId: string;
  occupationOther: string;
  openAccountType: string;
  politicalRelatePersonPosition: string;
  relatedPoliticalPerson: boolean;
  riskLevelDTO: RiskLevelDTO;
  spouseCardNumber: string;
  spouseCardType: string;
  spouseEnFirstname: string;
  spouseEnLastName: string;
  spousePassportCountry: string;
  spouseThFirstname: string;
  spouseThLastname: string;
  spouseTitle: string;
  spouseTitleOther: string;
  thFirstname: string;
  thLastname: string;
  title: string;
  titleOther: string;
  userId: number;
  username: string;
  vulnerableDetail: string;
  vulnerableFlag: boolean;
  workAddress: WorkAddressDTO;
  workAddressFlag: string;
  workPosition: string;
  isVerifyEmail: boolean;
  finnetCustomerNo: string;
  fatcaDate: Date;
  ndidRequestId: string;
}
