import { RouteInfo } from './sidebar-menu.metadata';
import { PermissionEnum } from '@app/core/variables/permission.enum';

// Sidebar menu Routes and data
export const ROUTES: RouteInfo[] = [
  {
    path: 'user',
    title: 'User',
    // icon: 'ic-account-circle',
    icon: 'ic-account-circle',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    permission: PermissionEnum.UseRoleManagement,
  },
  {
    path: '',
    title: 'Customer',
    icon: 'ic-supervisor',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    permission: PermissionEnum.CustomerList,
    submenu: [
      {
        path: '/customer/list',
        title: 'Customer List',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.CustomerList,
      },
      {
        path: 'customer/regulatory-monitoring',
        title: 'Regulatory Monitoring',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.CustomerRegulatoryMonitoring,
      },
    ]
  },
  // {
  //   path: '',
  //   title: 'Account Opening',
  //   icon: 'ic-account-box-multiple',
  //   class: 'has-sub',
  //   isExternalLink: false,
  //   submenu: [
  //     {
  //       path: 'account/open-account',
  //       title: 'Open Account',
  //       icon: '',
  //       class: '',
  //       badge: '',
  //       badgeClass: '',
  //       isExternalLink: false,
  //       submenu: []
  //     },
  //     {
  //       path: 'account/account-ats-approval',
  //       title: 'Account/ATS Approval',
  //       icon: '',
  //       class: '',
  //       badge: '',
  //       badgeClass: '',
  //       isExternalLink: false,
  //       submenu: []
  //     },
  //   ]
  // },
  {
    path: '',
    title: 'Agent',
    icon: 'ic-briefcase-account',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/agent/profile',
        title: 'Agent Profile',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.AgentProfile,
      },
      {
        path: '/agent/customer-service',
        title: 'Customer Service',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.AgentCustomerService,
      },
    ]
  },
  {
    path: '',
    title: 'Commission',
    icon: 'ic-briefcase-account',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/commission/tsr-incentive-rate',
        title: 'TSR Incentive Rate',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.CommissionTSRIncentiveRate,
      },
      {
        path: '/commission/payment',
        title: 'Payment',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.CommissionPayment,
      },
      {
        path: '/commission/commission-fee',
        title: 'Agent Fee Report',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.CommissionAgentFeeReport,
      },
    ]
  },
  {
    path: '',
    title: 'Order',
    icon: 'ic-order',
    class: 'has-sub',
    isExternalLink: false,
    submenu: [
      {
        path: 'order/transaction',
        title: 'Transaction',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.OrderTransaction,
      },
      {
        path: 'order/vulnerable-transaction',
        title: 'Vulnerable Transaction',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.OrderVulnerableTransaction,
      },
      {
        path: 'order/order-placement',
        title: 'Order Placement',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.OrderPlacement,
      },
      {
        path: 'order/sync-transaction',
        title: 'Sync Transaction',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.OrderTransaction,
      },
    ]
  },
  {
    path: 'fund',
    title: 'Fund Data',
    icon: 'ic-cash-multiple',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    permission: PermissionEnum.FundData,
  },
  {
    path: '',
    title: 'Index Type',
    icon: 'ic-cash-multiple',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: 'index-type',
        title: 'Index Type',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.IndexType,
      },
      {
        path: 'fund-index/fund-index-type',
        title: 'Fund Index Type',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.FundIndex,
      },
      {
        path: 'fund-index/fund-for-index-type',
        title: 'Fund for Index Type',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        permission: PermissionEnum.FundsAllIndex,
      },
    ]
  },
  {
    path: 'custom-notification',
    title: 'Custom Notification',
    icon: 'ft-search',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    permission: PermissionEnum.CustomNotification,
  },
  {
    path: 'content-management',
    title: 'Content',
    icon: 'ic-content-paste',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    permission: PermissionEnum.Content,
  },
  {
    path: 'audit-risk',
    title: 'Audit Risk',
    icon: 'ic-eye-circle',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    permission: PermissionEnum.AuditRisk,
  },
  {
    path: 'news',
    title: 'News',
    icon: 'fa fa-newspaper-o',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    permission: PermissionEnum.News,
  },
];
